/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var m=(i,e)=>{for(var t in e)o(i,t,{get:e[t],enumerable:!0})},f=(i,e,t,l)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of d(e))!h.call(i,r)&&r!==t&&o(i,r,{get:()=>e[r],enumerable:!(l=p(e,r))||l.enumerable});return i};var v=i=>f(o({},"__esModule",{value:!0}),i);var w={};m(w,{VIEW_TYPE_TIDLE:()=>a,default:()=>n});module.exports=v(w);var s=require("obsidian"),a="tidle-view",n=class extends s.Plugin{onload(){this.registerView(a,t=>new c(t)),(0,s.addIcon)("tidle-icon",`
      <svg viewBox="0 0 27 43" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M18.6066 42.462C16.0546 42.462 13.7886 42.044 11.8086 41.208C9.82865 40.372 8.26665 39.03 7.12265 37.182C6.02265 35.334 5.47265 32.892 5.47265 29.856V17.184H-0.00535148V9.33H5.73665V0.0239975H16.2966V9.33H25.2726V17.25H16.3627V29.526C16.3627 31.198 16.7586 32.342 17.5506 32.958C18.3866 33.574 19.3767 33.882 20.5206 33.882C21.2246 33.882 21.9946 33.816 22.8306 33.684C23.7107 33.508 24.3926 33.266 24.8766 32.958L26.6586 40.746C25.5586 41.362 24.2826 41.802 22.8306 42.066C21.4226 42.33 20.0146 42.462 18.6066 42.462Z"
          fill="currentColor"
        />
      </svg>
      `),this.addRibbonIcon("tidle-icon","Open sidebar",()=>this.activateView().catch(console.error)).classList.add("tidle-ribbon-icon"),this.addCommand({id:"open-tidle",name:"Open sidebar",callback:()=>this.activateView().catch(console.error)})}onunload(){this.app.workspace.getLeavesOfType(a).forEach(e=>e.detach())}async activateView(){let e=this.app.workspace.getLeavesOfType(a);if(e.length>0){this.app.workspace.revealLeaf(e[0]);return}let t=this.app.workspace.getLeaf(!0);await t.setViewState({type:a,active:!0}),this.app.workspace.revealLeaf(t)}},c=class extends s.ItemView{constructor(t){super(t);this.iframe=null}getViewType(){return a}getDisplayText(){return"Tidle"}onOpen(){this.contentEl.empty(),this.contentEl.classList.add("tidle-view-container"),this.iframe=document.createElement("iframe"),this.iframe.src="https://tidle.app/main",this.iframe.title="Tidle",this.iframe.classList.add("tidle-iframe"),this.contentEl.appendChild(this.iframe)}onClose(){this.iframe&&(this.iframe.src="about:blank",this.iframe.remove(),this.iframe=null),this.contentEl.classList.remove("tidle-view-container")}};
